[package]
name = "application"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../domain" }
shared = { path = "../shared" }
infrastructure = { path = "../infrastructure" }
anyhow.workspace = true
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
md5 = "0.8"
serde_json = "1.0"
