[package]
name = "application"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../domain" }
shared = { path = "../shared" }
infrastructure = { path = "../infrastructure" }
anyhow.workspace = true
tokio.workspace = true
md5 = "0.7"
uuid.workspace = true
serde_json.workspace = true
serde.workspace = true
colored.workspace = true
num_cpus.workspace = true
tokio-stream = "0.1"
futures = "0.3"
regex = "1.10"
once_cell = "1.19"

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "performance_benchmarks"
harness = false
