[package]
name = "presentation"
version = "0.1.0"
edition = "2021"

[dependencies]
application = { path = "../application" }
infrastructure = { path = "../infrastructure" }
shared = { path = "../shared" }
domain = { path = "../domain" }
clap.workspace = true
colored.workspace = true
dialoguer.workspace = true
arboard.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
bincode = "1.3"
chrono = { version = "0.4", features = ["serde"] }
pdf-extract = "0.7"
docx-rs = "0.4"
reqwest = { version = "0.12", features = ["blocking"] }
tokio.workspace = true
git2 = "0.18"
flume = "0.11"